SELECT * FROM (
SELECT
A.REST_ID
,A.REST_NAME
,A.FOOD_TYPE
,A.FAVORITES
,A.ADDRESS
,(SELECT ROUND(AVG(B.REVIEW_SCORE),2) FROM REST_REVIEW B WHERE B.REST_ID = A.REST_ID) SCORE
FROM REST_INFO A
WHERE A.ADDRESS LIKE '서울%'
)
WHERE SCORE IS NOT NULL
ORDER BY SCORE DESC , FAVORITES DESC